name: Feature request
description: Request a new feature for the mod.
labels: [ feature request ]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that feature requests are aligned with the core concept of the mod.
        Integration requests also count as a feature request and should be issued here.
  - type: dropdown
    id: type
    attributes:
      label: Feature type
      description: Wether this is an integration request or a feature request for the core mod.
      options:
        - Mod Feature
        - Mod Integration
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: A good addition would be... I would like this mod to be compatible...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.