name: 'Release'

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: git fetch origin --tags
        shell: bash
      - name: Get release tag
        shell: bash
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
        with:
          cache-read-only: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run datagen
        run: ./gradlew runData
      - name: Check that datagen ran
        run: test -d ./src/generated/resources/.cache
      - name: Build
        run: ./gradlew build
        env:
          TAG: ${{ github.event.release.tag_name }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/**.jar
          retention-days: 2

  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: download

      - uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          name: Phasorite Networks ${{ github.event.release.tag_name }}

          loaders: neoforge
          java: 21
          version: ${{ github.event.release.tag_name }}
          changelog-file: CHANGELOG.md
          game-versions: 1.21.1

          curseforge-id: 1140963
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-dependencies: |
            owo-lib | depends
            kotlin-for-forge | depends

          files: download/!(*-@(sources)).jar