name: 'Release'

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get release tag
        shell: bash
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "$TAG"

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
        with:
          cache-read-only: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run datagen
        run: ./gradlew runData

      - name: Check that datagen ran
        run: test -d ./src/generated/resources/.cache

      - name: Build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/**.jar
          retention-days: 2

  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: download

      - name: Get release tag
        shell: bash
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "$TAG"

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: Phasorite Networks ${{ github.event.release.tag_name }}

          loaders: neoforge
          java: 21
          version: ${{env.TAG}}
          changelog-file: CHANGELOG.md
          game-versions: 1.21.1
          dependencies: |
            owo-lib | depends
            kotlin-for-forge | depends

          curseforge-id: 1140963
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: ZEvlCeIH
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: download/!(*-@(sources)).jar